apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  annotations: {}
  name: test-prometheus-job
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: 'tiagotxm/spark:v3.1.1-prometheus'
  imagePullPolicy: IfNotPresent
  sparkConf:
    spark.sql.streaming.metricsEnabled: 'true'
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    metricsPropertiesFile: /opt/spark/monitoring/metrics.properties
    prometheus:
      jmxExporterJar: /opt/spark/jars/jmx_prometheus_javaagent-0.17.2.jar
      configFile: /opt/spark/monitoring/prometheus.yaml
      port: 9090
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  arguments:
    - "100000"
  # timeToLiveSeconds: 120
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: config-vol-properties
      configMap:
        name: prometheus-spark-conf-map
        items:
          - key: "metrics.properties"
            path: "metrics.properties"
          - key: "prometheus.yaml"
            path: "prometheus.yaml"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    volumeMounts:
      - name: config-vol-properties
        mountPath: /opt/spark/monitoring
    labels:
      version: 3.1.1
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    volumeMounts:
      - name: config-vol-properties
        mountPath: /opt/spark/monitoring
    labels:
      version: 3.1.1